### PR TITLE
Update bot.py

### PR DESCRIPTION
**Pull request by Divyanshu960**
Added an avatar command to display mentioned user's Avatar

### CODE REVIEW

**Comment by kanakmi** [comment]
Hey @Divyanshu960 
Can you please add a screenshot covering both the cases for this command? Also please include it in the help command.

**Comment by kanakmi** [comment]
Also let me know if you're participating in Hacktoberfest. Will add that label to the PR.

**Comment by Divyanshu960** [comment]
Yes sure bhaiya, will add screenshots for its usecases . And yes I am
participating in the Hacktoberfest .
Thank you

**Review by kanakmi — APPROVED** [review]
I have made some fixes and am approving these changes. 
Thanks for your contribution @Divyanshu960

**Pull request merged**
